# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release ASC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: |
          dotnet restore
          dotnet tool install --global wix
          wix eula accept wix7
          wix extension add -g WixToolset.UI.wixext
          
      - name: Build Release
        id: build
        run: dotnet build -c Release --no-restore
             
      - name: Build Installer
        shell: powershell
        run: |
          $BuildExe = (Get-Item "ASC.Installer/bin/Release/net472/ASC.Installer.exe").FullName
          & $BuildExe

      - name: Get File Info
        id: file_info
        shell: powershell
        run: |
          $FileInfo = Get-ChildItem -Filter '*.msi' -Recurse -File
          $FileInfo.Count
          $FileInfo.Name -match '\-(.*?)\.msi'
          echo "file_path=$($FileInfo.FullName)" >> $env:GITHUB_OUTPUT
          echo "file_name=$($FileInfo.Name)" >> $env:GITHUB_OUTPUT
          echo "build_version=$($Matches[1])" >> $env:GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.file_info.outputs.file_name }}
          files: ${{ steps.file_info.outputs.file_path }}
          tag_name: ${{ steps.file_info.outputs.build_version }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                    

    
